name: 'MCU Build Action'
description: 'Composite Action for building MCU tools'
inputs:
  junit_files:
    description: 'Path of the junit files'
    required: true
  output_file:
    description: 'output html file path'
    required: false
    default: "./test_report.html"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/scripts/requirements.txt

    - name: Merge junit test reports
      shell: bash
      run: |
        python $GITHUB_ACTION_PATH/scripts/merge_test_reports.py -i ./${{ inputs.junit_files }} -o ./merged_test_results.xml

    - name: Generate HTML reports
      shell: bash
      run: |
        junit2html ./merged_test_results.xml ./${{ inputs.output_file }}
