name: 'JUnit to HTML'
description: 'Merge JUnit files and generate consolidated HTML report'
inputs:
  junit_files:
    description: 'Path of the JUnit files'
    required: true
  output_file:
    description: 'Output HTML file path'
    required: false
    default: "./test_report.html"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/scripts/requirements.txt

    - name: Merge junit test reports
      shell: bash
      run: |
        python $GITHUB_ACTION_PATH/scripts/merge_test_reports.py -i ./${{ inputs.junit_files }} -o ./merged_test_results.xml

    - name: Generate HTML reports
      shell: bash
      run: |
        junit2html ./merged_test_results.xml ./${{ inputs.output_file }}
